[versions]
kotlin = "2.3.0" # https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm
java = "21"
changelog = "2.5.0" # https://plugins.gradle.org/plugin/org.jetbrains.changelog
gradleIntelliJPlugin = "2.10.5" # https://plugins.gradle.org/plugin/org.jetbrains.intellij.platform
intellijJunit = "4.13.2" # !!! ВАЖНО !!! Пока intellij platform использует старый Junit внутри, поэтому надо добавлять, чтобы был корректный запуск
junit = "6.0.1" # https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
kotest = "6.0.7" # https://plugins.gradle.org/plugin/io.kotest
dokka = "2.1.0"  # https://plugins.gradle.org/plugin/org.jetbrains.dokka
kover = "0.9.4"  # https://plugins.gradle.org/plugin/org.jetbrains.kotlinx.kover
reflections = "0.10.2" # https://mvnrepository.com/artifact/org.reflections/reflections
mockk = "1.13.13" # https://mvnrepository.com/artifact/io.mockk/mockk

[libraries]
intellij-junit = { group = "junit", name = "junit", version.ref = "intellijJunit" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
dokkaVersioningPlugin = { module = "org.jetbrains.dokka:versioning-plugin", version.ref = "dokka" }
reflections = { module = "org.reflections:reflections", version.ref = "reflections" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }


[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }

[bundles]
test = ["intellij-junit", "kotest-assertions-core", "junit-jupiter-api", "reflections", "mockk"]