[versions]
# plugins
kotlin = "2.2.21"
changelog = "2.2.1"
gradleIntelliJPlugin = "2.5.0"
intellijJunit = "4.13.2"
junit = "6.0.1"
kotest = "6.0.0"
dokka = "2.0.0"

[libraries]
intellij-junit = { group = "junit", name = "junit", version.ref = "intellijJunit" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

[bundles]
test = ["intellij-junit", "kotest-assertions-core", "junit-jupiter-api"]